// export * from './user';
// export * from './institute';
// export * from './products';
// export * from './major';
// export * from './role';
// export * from './_profile';
// export * from './_rule';
export * from './_api';
// export * from './_chart';
// // export * from './_user';
// export * from './_geo';
export * from './_pois';
